//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupWPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupWPF.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško prvenstvo.
        /// </summary>
        public static string champMan {
            get {
                return ResourceManager.GetString("champMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko prvenstvo.
        /// </summary>
        public static string champWoman {
            get {
                return ResourceManager.GetString("champWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa kod.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljenih golova.
        /// </summary>
        public static string conceded {
            get {
                return ResourceManager.GetString("conceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika.
        /// </summary>
        public static string diff {
            get {
                return ResourceManager.GetString("diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neriješeno.
        /// </summary>
        public static string draw {
            get {
                return ResourceManager.GetString("draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski jezik.
        /// </summary>
        public static string langEng {
            get {
                return ResourceManager.GetString("langEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski jezik.
        /// </summary>
        public static string langHrv {
            get {
                return ResourceManager.GetString("langHrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string lblSet {
            get {
                return ResourceManager.GetString("lblSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porazi.
        /// </summary>
        public static string losses {
            get {
                return ResourceManager.GetString("losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi prvenstvo.
        /// </summary>
        public static string pickChampionship {
            get {
                return ResourceManager.GetString("pickChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi jezik.
        /// </summary>
        public static string pickLang {
            get {
                return ResourceManager.GetString("pickLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlučivost zaslona.
        /// </summary>
        public static string pickScreenRes {
            get {
                return ResourceManager.GetString("pickScreenRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrano utakmica.
        /// </summary>
        public static string played {
            get {
                return ResourceManager.GetString("played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeno golova.
        /// </summary>
        public static string scored {
            get {
                return ResourceManager.GetString("scored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamjene.
        /// </summary>
        public static string subs {
            get {
                return ResourceManager.GetString("subs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistike.
        /// </summary>
        public static string teamStat {
            get {
                return ResourceManager.GetString("teamStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede.
        /// </summary>
        public static string wins {
            get {
                return ResourceManager.GetString("wins", resourceCulture);
            }
        }
    }
}
